bcgov/EDUC-STUDENT-ADMIN

- frontend/src/components/common/PenMatchResultsTable.vue
- frontend/src/components/penreg/penrequest-batch/PrbStudentDetailsDisplay.vue
- frontend/src/utils/common.js
1. enabling action on refresh, running pen match
2. Adding missing checks for user match scenario to disable action buttons
3. Removed some unnecessary code
4. Call pen match only when validation is successful
> Multiple items , see details

- frontend/src/components/common/StudentDetailCommon.vue
- frontend/src/components/util/TertiaryButton.vue
- frontend/src/main.js
new copy button and on paste bold formatted key values implemented
> Please refer to ticket : PEN-1037

- frontend/src/components/common/CompareDemographicsCommon.vue
PEN-1114:  usual names are displayed if different from legal names in compare/view.
> PEN-1114:  usual names are displayed if different from legal names in compare/view.

- frontend/src/components/penreg/penrequest-batch/ArchivedRequestBatchList.vue
- frontend/src/components/penreg/penrequest-batch/LoadFailedBatchList.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchDataTable.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchList.vue
- frontend/src/utils/constants.js
View Re-Archived files is initially implemented.
> View Re-Archived files is initially implemented.

- frontend/src/components/penreg/penrequest-batch/PenRequestBatchDisplay.vue
Please refer to ticket PEN-1267
> removed delete file from dropdown, changed wordings as required

- frontend/src/components/penreg/penrequest-batch/ArchivedRequestBatchDisplay.vue
- frontend/src/components/util/FormattedTextField.vue
- frontend/src/utils/format.js
- frontend/src/utils/validation.js
"Change date input on Archived PEN Request File list screen so that slashes are not required, but once entered are displayed as 2020/09/18 (same pattern as DOB input on Student Details) "
> code changes for

- frontend/src/components/penreg/penrequest-batch/PrbStudentDetailsDisplay.vue
- frontend/src/components/penreg/penrequest-batch/PrbStudentListDisplay.vue
New changes to add hotkey functionality.
> Added hot keys.

- frontend/src/components/Home.vue
- frontend/src/components/MessagesPage.vue
- frontend/src/router.js
- frontend/src/utils/constants.js
Added new MessagesPage component. 
Prototyped the side menu on the page, however styling still needs to be finessed. 
Messages section has not been completed yet.
> WIP Feature/pen 1795 added MessagesPage component, routing and side menu

- frontend/src/components/MessagesPage.vue
> Feature/pen 1795 Prototype of messagesPage with messages. 

- frontend/src/components/MessagesPage.vue
Added function to click on message row for action. Added bolded font to rows where message is unread
> WIP PEN-1795 row click action and unread message styling. 

- frontend/src/components/MessagesPage.vue
related to pen-1830 pen-1826 pen-1826 pen-1829
Adding ability to switch between different message inboxes. Might have different implementation later on.
> Feature/pen 1795 WIP to allow changing to different message types

- frontend/src/components/penreg/penrequest-batch/ArchivedRequestBatchDisplay.vue
- frontend/src/mixins/searchMixin.js
the archived pen request files page
> PEN-1815: Clear mincode field when clicking the clear button on 

- frontend/src/utils/format.js
> Remove "Not provided" phone number feedback

- frontend/src/components/institute/AuthorityDetails.vue
- frontend/src/components/institute/DistrictDetails.vue
- frontend/src/components/institute/SchoolDetails.vue
- frontend/src/components/util/PrimaryButton.vue
- Fixed cancel button issue
- Removed italic font from css
- Added permission check for edit links
> EDX-643: View of "missing data" on SCH | DIS | AUTH Details

- frontend/src/components/institute/AuthoritiesContacts.vue
- frontend/src/components/institute/AuthoritiesList.vue
- frontend/src/components/institute/AuthorityContact.vue
- frontend/src/components/institute/AuthorityDetails.vue
- frontend/src/components/institute/DistrictContact.vue
- frontend/src/components/institute/DistrictContacts.vue
- frontend/src/components/institute/DistrictDetails.vue
- frontend/src/components/institute/SchoolContact.vue
- frontend/src/components/institute/SchoolContacts.vue
- frontend/src/components/institute/SchoolDetails.vue
- frontend/src/components/institute/SchoolList.vue
> hide buttons that require missing permissions to use

- frontend/src/components/secure-message/AccessDistrictUsersPage.vue
- frontend/src/components/secure-message/AccessUserCard.vue
- frontend/src/components/secure-message/AccessUsersPage.vue
Also adds missing spinner
Jira: EDX-1025
> rework AccessUserCards into uniform rows

- frontend/src/components/institute/AuthorityContact.vue
- frontend/src/components/institute/EditAuthorityContactPage.vue
- frontend/src/components/institute/NewAuthorityContactPage.vue
> remove references to authority contact jobTitle

- frontend/src/components/secure-message/MessageDisplay.vue
> Fix "disabled" documents on unread messages

- frontend/src/components/institute/EditDistrictContactPage.vue
> update district contact title to "Position Title"

- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/SchoolHistory.vue
- frontend/src/components/institute/SchoolHistoryDetail.vue
> Add school reporting requirement code to school move ui

- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/NewSchoolPage.vue
- frontend/src/components/institute/SchoolList.vue
> Constrain category codes for edge-case districts

- frontend/src/utils/institute/formRules.js
> feat: require https for website urls

- frontend/src/components/institute/AuthorityDetails.vue
- frontend/src/components/institute/DistrictDetails.vue
- frontend/src/components/institute/EditAuthorityContactPage.vue
- frontend/src/components/institute/EditDistrictContactPage.vue
- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/NewAuthorityContactPage.vue
- frontend/src/components/institute/NewAuthorityPage.vue
- frontend/src/components/institute/NewDistrictContactPage.vue
- frontend/src/components/institute/NewSchoolPage.vue
- frontend/src/components/institute/common/Details.vue
- frontend/src/utils/institute/formRules.js
Jira Tickets:
- EDX-1387
- EDX-1388
- EDX-1389
- EDX-1390
- EDX-1395
- EDX-1396
- EDX-1397
> Prohibit the use of special characters in select fields where downstream impact may occur

- frontend/src/components/institute/common/EditSchoolContactPage.vue
- frontend/src/components/institute/common/NewSchoolContactPage.vue
> feat: prohibit special chars in school contacts

- frontend/src/components/institute/SchoolList.vue
> fix: School Category being required for search

- frontend/src/components/institute/SchoolList.vue
> fix: overflowing field values

- backend/src/components/institute/institute.js
- frontend/src/components/institute/NewSchoolPage.vue
My code changes appears in lines between 19 and 30, and at line 424.
> EDX-1424 Add "Legacy Safe School Name" to New School Form

- frontend/src/components/institute/SchoolDetails.vue
- frontend/src/components/institute/common/Details.vue
- frontend/src/components/institute/common/SchoolHistoryDetail.vue
- frontend/src/utils/institute/formRules.js
EDX-1495: Allow "&" in the Mailing/Physical Address section and in the "Position Title " field.
> EDX- 1386, 1426: Legacy Safe School Name to School History and Details page

- frontend/src/components/util/NavBar.vue
> fix: missing overflow for navigation drawer

- backend/src/components/edx/exchange.js
- frontend/src/components/secure-message/ExchangePage.vue
EDX-1513: See Indicator in Inbox when a message has an attachment
> EDX-1508: Filter by Unclaimed

- frontend/src/components/common/DocumentUpload.vue
- frontend/src/components/institute/DistrictDetails.vue
EDX-1605: Allow upper case extensions
> EDX-1038: District Schools List from District Contact Information

- frontend/src/components/secure-message/NewMessagePage.vue
Added spacing between alert and add student button.
> Bugs Fix - New message alert spacing

- frontend/src/components/secure-message/AccessDistrictUsersPage.vue
> Bug Fix for EDX-1619

- frontend/src/components/institute/authority/AuthoritiesContacts.vue
- frontend/src/components/institute/authority/AuthorityContact.vue
- frontend/src/components/institute/authority/NewAuthorityContactPage.vue
> Sort authority reps to the top of authority contacts

- frontend/src/components/Home.vue
> Add welcome message to dashboard when there are no roles that display info.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/RequestDetail.vue
- frontend/src/components/RequestsDisplay.vue
- frontend/src/components/admin/stats/MergedStudentsStatsDataTable.vue
- frontend/src/components/common/CompareDemographicsCommon.vue
- frontend/src/components/common/PenMatchResultsTable.vue
- frontend/src/components/common/StudentDetailsInfoPanel.vue
- frontend/src/components/institute/AuthoritiesList.vue
- frontend/src/components/institute/DistrictList.vue
- frontend/src/components/institute/SchoolDetails.vue
- frontend/src/components/institute/SchoolList.vue
- frontend/src/components/institute/common/AddSchoolFunding.vue
- frontend/src/components/institute/common/SchoolFunding.vue
- frontend/src/components/institute/common/SchoolHistory.vue
- frontend/src/components/nominal-roll/NomRollStudentSearchResults.vue
- frontend/src/components/penreg/penrequest-batch/HeldRequestBatchList.vue
- frontend/src/components/penreg/penrequest-batch/LoadFailedBatchList.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchDataTable.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchHistoryModal.vue
- frontend/src/components/penreg/penrequest-batch/PrbStudentSearchResults.vue
- frontend/src/components/penreg/student-search/StudentSearchResults.vue
- frontend/src/components/penreg/student/StudentAuditHistory.vue
- frontend/src/components/penreg/student/StudentSLDHistory.vue
- frontend/src/components/secure-message/ExchangePage.vue
- frontend/src/components/util/DatePicker.vue
Jira Tickets: EDX-1841 & EDX-1931
To facilitate these fixes I reverted the Vuetify version from nightly to stable here: https://github.com/bcgov/EDUC-STUDENT-ADMIN/commit/6e54d81405f458d149362d71759d8b764c552cc7 - This falls in line with the school side application.  Doing this also fixed the broken Vuetify grid features.
This ended up breaking _all of the v-data-tables_ because of the removal of the `raw` accessor. 
For future reference, `item.raw` is deprecated and its usage is being pruned out of Vuetify updtream.  See https://github.com/vuetifyjs/vuetify/issues/18354
> Multiple bug fixes

- backend/src/components/institute/institute.js
> fix: remove admin check for school notes

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/RequestDetail.vue
- frontend/src/components/RequestsDisplay.vue
- frontend/src/components/admin/stats/MergedStudentsStatsDataTable.vue
- frontend/src/components/common/CompareDemographicsCommon.vue
- frontend/src/components/common/PenMatchResultsTable.vue
- frontend/src/components/common/StudentDetailsInfoPanel.vue
- frontend/src/components/institute/AuthoritiesList.vue
- frontend/src/components/institute/DistrictList.vue
- frontend/src/components/institute/SchoolList.vue
- frontend/src/components/institute/common/Details.vue
- frontend/src/components/institute/common/SchoolFunding.vue
- frontend/src/components/institute/common/SchoolHistory.vue
- frontend/src/components/nominal-roll/NomRollStudentSearchResults.vue
- frontend/src/components/penreg/penrequest-batch/HeldRequestBatchList.vue
- frontend/src/components/penreg/penrequest-batch/LoadFailedBatchList.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchDataTable.vue
- frontend/src/components/penreg/penrequest-batch/PenRequestBatchHistoryModal.vue
- frontend/src/components/penreg/penrequest-batch/PrbStudentSearchResults.vue
- frontend/src/components/penreg/student-search/StudentSearchResults.vue
- frontend/src/components/penreg/student/StudentAuditHistory.vue
- frontend/src/components/penreg/student/StudentSLDHistory.vue
- frontend/src/components/secure-message/ExchangePage.vue
This reverts commit c07e18e993333930cc7f6968304fdb0ecbb8e94b.
Also fixes multi-select boxes on the Details page
Jira: EDX-1931 & EDX-1946
> fix: vuetify version 3.3.15

- frontend/src/components/secure-message/AccessDistrictUsersPage.vue
- frontend/src/components/secure-message/AccessSchoolUsersPage.vue
> fix: prepended icon for primary code info

- frontend/src/components/institute/NewSchoolPage.vue
> feat: update initial edx school account prompt

- frontend/src/components/institute/NewSchoolPage.vue
> fix: offshore schools do not require an admin

- frontend/src/components/institute/NewSchoolPage.vue
> fix: offshore schools do require an admin

- backend/src/components/edx/exchange.js
> fix: don't mutate the data mid transit

- backend/src/components/edx/exchange.js
Add a sanitizer to initial user flow.
> feat: re-add user sanitization and add feedback

- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/common/SchoolMove.vue
- stops schools from being moved within the same district
> EDX-2008 - stops schools from being moved to or from the Yukon.

- frontend/src/components/institute/NewAuthorityPage.vue
> Fix authority type sorting and checkbox click area

- frontend/src/components/secure-message/InstituteAccessPage.vue
> fix: simplify dom for InstituteAccessPage

- backend/src/components/edx/exchange.js
Found bug while fixing EDX-2027
> fix: bad request error when all fields are empty

- frontend/src/components/institute/NewSchoolPage.vue
> fix: submit addresses with new school payload

- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/common/SchoolMove.vue
> fix: some UI defects for Move School

- frontend/src/components/institute/MoveSchoolPage.vue
> Followup bug fixes for SchoolMove

- frontend/src/components/institute/SchoolList.vue
- frontend/src/components/institute/common/Details.vue
> fix: link in toast open in new tab

- frontend/src/components/institute/MoveSchoolPage.vue
> Prevent schools from being moved into post-secondary institutions

- frontend/src/components/institute/MoveSchoolPage.vue
- frontend/src/components/institute/NewSchoolPage.vue
> fix: restrict column for sameAsMailingAddress

- frontend/src/components/penreg/penrequest-batch/PenRequestBatchDisplay.vue
- frontend/src/components/util/ConfirmationDialog.vue
> fix: simplify/standardsize headers in dialogues

- frontend/src/components/penreg/student-search/StudentAdvancedSearch.vue
> Fix inability to put spaces in name fields on student advanced search

- frontend/src/components/common/StudentDetailCommon.vue
> fix: copy-to-clipboard on StudentDetailCommon

- frontend/src/components/data-collection/ReportSection.vue
- typo
- double loading spinner
- report not disappearing after switching report type
> Some ui fixes for the reports section

- backend/src/components/sdc/sdc.js
- frontend/src/utils/sdc/collectionTableConfiguration.js
default filter for all student reports to omit students that are deleted or have warnings
> Min | Reports | Public/IND School Students Report | Minor Defects 

- frontend/src/components/assessments/AssessmentSessions.vue
- frontend/src/components/assessments/sessions/SessionEdit.vue
Change Details:
1. Changes to include School year in the session management screen.
2. Sort historical records by active until date.
3. Make Close date mandatory.
> EAC-8 (Minor changes)

- backend/src/components/cache-service.js
- backend/src/config/index.js
- backend/src/schedulers/cache-service-scheduler.js
- frontend/src/components/assessments/registrations/StudentRegistrationsFilter.vue
-Changes to cache assessments. 
- Unit Testing
- General regression on filtering registrations.
> Changes to cache assessments

- frontend/src/components/data-collection/DistrictMonitoring.vue
- frontend/src/components/data-collection/IndySchoolMonitoring.vue
Changes to the monitoring screen
> Changes to monitoring screens for historical.

- backend/src/validations/eas.js
- frontend/src/components/assessments/AssessmentSessions.vue
- frontend/src/components/assessments/registrations/StudentRegistrations.vue
Change Details:
1. Changes to include assessmentValidations.
2. Change from modal to bottom sheet.
3. filtering of records at top panel by schoolyear.
Unit Testing:
1. General regression,
> EAC-40: Minor UI changes 

- backend/src/components/validator.js
Change Details:
Log yup validation on backend 
Unit Testing:
ACs.
> Changes to log yup validation.

- frontend/src/components/common/AddStudent.vue
- frontend/src/components/data-collection/PenMatchStudentDetails.vue
Description: Option to manually assign PEN.
> EDX:3081 - PR to assign PEN manually.

- backend/src/components/gdc/gdc.js
- frontend/src/components/gdc/insights/CollectionInsights.vue
- frontend/src/components/gdc/insights/SchoolCategoryTable.vue
also whole number percentages and search/filter bar formatting/layout
> fix difference between insights tab and school category table totals
